-- Public bucket for export artifacts (PNGs, ZIPs) generated by the
-- carousel exporter and video renderer. Filenames are content-hashed so
-- collisions = identical bytes; upserts are safe.
insert into storage.buckets (id, name, public)
values ('readopp-exports', 'readopp-exports', true)
on conflict (id) do nothing;
